### PR TITLE
feat: Exposing the currently loaded FeatureToggle collection outside of the…

### LINKED ISSUE #66: Add Type to feature toggle object and expose the feature toggle collection readonly publicly.
**Is your feature request related to a problem? Please describe.**
Feature parity with other client. Similar to how the node client allows you to get all feature flag definitions: https://github.com/Unleash/unleash-client-node#3-use-unleash 
Also, the endpoint to grab features from the server "client/features" includes the "Type" field which could be useful if we have access to the entire collection.

**Describe the solution you'd like**
Add "Type" as a string to the FeatureFlag class.
Expose a public getter that returns whatever the most recent collection of feature flag definitions exist.  This could be as simple as adding this to DefaultUnleash.cs
`public ICollection<FeatureToggle> FeatureToggles { get { return services.ToggleCollection.Instance.Features; } }`
Doing this would require adjusting the access modifier on some classes like FeatureToggle or would require some sort of mapping to a new public friendly entity.

**Describe alternatives you've considered**
The only other means of doing this would be to hit the api endpoint manually or directly hitting the database. Neither of these are great options.

**Additional context**
Currently, using the net client, a consumer can only grab a flag by name.  Simply exposing the feature flag definition collection would allow a consumer to grab toggles on a type.

### PR DESCRIPTION
**Pull request by brcpar**
… sdk.  Adding "Type" to the FeatureToggle class to be consistent with what comes from the api.  Adjusting tests and access modifiers to account for changes.  This addresses issue#66

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

I exposed the ICollection<FeatureToggle> of the currently loaded collection of toggles as a public getter so that it can be access outside of the sdk.   I also added Type property to the FeatureToggle class to make consistent with what's coming across the unleash client api.

Fixes #66 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Ran local unleash server and tested access against for new field and also ensure newly exposed property was accessible properly.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ivarconr** [comment]
Thanks @brcpar. 

Do you happen to understand why AppVeyor fails with:

```
Error: Unknown command 'AppVeyor'.
       build.cake -target=AppVeyor
                          ^^^^^^^^ No such command
```

**Comment by brcpar** [comment]
I'm not sure what could have caused that.  That appears to be something with the CI build.  I built using the dotnet cli fine before PRing.  I can try to take a look at what specifically could be failing the cake build.

**Comment by brcpar** [comment]
I haven't had time to debug it yet, but I pulled master and tried to run the cake build and it too fails.  It appears to be something already in master causing this. I might have more time to poke around at it in a few hours.

**Comment by brcpar** [comment]
Actually, after just running the ps command, I noticed if you specify target to being default, it doesn't the same thing and the command line it generates which fails is:
`.\tools\Cake\Cake.exe build.cake -target=default`
However, this appears to build:
`.\tools\Cake\Cake.exe build.cake --target=default`

I'm not very savvy with cake builds, but it appears as though build.ps1 needs to be updated to pass `--target` rather than `-target` in the script generation at the bottom.

@ivarconr, that's just my guess.

**Comment by ivarconr** [comment]
Ok, fixed that on master, do you mind rebase your branch against master?

**Comment by brcpar** [comment]
I rebased your changes into my branch and it's now failing with an error on gitversion.  I'm not familiar enough with gitversion to say why it's failing.  Locally, gitversion produces output without any exceptions.

**Comment by ivarconr** [comment]
The gitversion is called as a result of an argument error which was a result of changing the arguments (from -target it --target). I will try to have a deep look at this tomorrow. Funny the PR i created seems to work just fine.

**Comment by ivarconr** [comment]
Ok, sorry for the back an forth (I had lost access to the appveyor project), but restored that and now fixed the build. Would you mind rebase another time from master? 

Except from that this PR makes sense, and is good to merge!

**Review by ivarconr — APPROVED** [review]

**Pull request merged**
