### PR TITLE
Added key exist check to timers

### PR DESCRIPTION
**Pull request by kodiak74**
# Description

Addressing System.Collections.Generic.KeyNotFoundException we have experienced.

Fixes # (issue)

Preventing a KeyNotFoundException if timer does not exist
- [X ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sighphyre** [comment]
Hey @kodiak74, thanks for the submission! So just a glance, I'm not sure why this exception is being raised for you, there's no obvious code sequence I can spot that should be triggering this. Before we merge this, I just want to be sure we actually track down the issue and not hide it. Can you tell me a little about how you're using Unleash? Is this in a heavily threaded environment or something? Also what version of .NET are you running and what version of the SDK? Finally, could you tell me a little about how often you're seeing this and under what circumstances it happens? Thank you!

Also... roping @daveleek, since his .NET is better than mine.

**Comment by kodiak74** [comment]
> Hey @kodiak74, thanks for the submission! So just a glance, I'm not sure why this exception is being raised for you, there's no obvious code sequence I can spot that should be triggering this. Before we merge this, I just want to be sure we actually track down the issue and not hide it. Can you tell me a little about how you're using Unleash? Is this in a heavily threaded environment or something? Also what version of .NET are you running and what version of the SDK? Finally, could you tell me a little about how often you're seeing this and under what circumstances it happens? Thank you!
> 
> Also... roping @daveleek, since his .NET is better than mine.

The problem manifests itself when running local testing for our API - the `dotnet test` code is running in a threaded fashion and running up and tearing down tests quite rapidly. Wanting to make sure that tests are successful so our CI/CD pipeline doesn't break. We are running 6.0.402.  Should point out it works fine in operation of the application - just the testing, hence the change to make the code a bit more robust.

**Comment by daveleek** [comment]
I had a look last night myself, and couldn't spot an immediate potential culprit either. The dictionary isn't static so seems unlikely that it's a shared state issue. The suggested change should be harmless, so no objections here. Would be interesting to get a repro going to figure out exactly what happens

**Review by sighphyre — APPROVED** [review]
LGTM

**Pull request merged**
