### PR TITLE
chore: change context defaults to null - fixes flexiblestrat

### PR DESCRIPTION
**Pull request by daveleek**
# Description

This fixes an issue with Flexible rollout strategy - stickiness would be resolved to an empty (non null) string instead of defaulting to random number when context isn't provided

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Created new unit tests
- [x] Ran existing tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by sighphyre — APPROVED** [review]
Ye!

**Review by thomasheartman — APPROVED** [review]
Nice! 😄 This is very nice 💯 How does it handle cases where the rollout isn't 100? Like 97? Is that done randomly then, or is it always false?

**Comment by sighphyre** [comment]
> Nice! smile This is very nice 100 How does it handle cases where the rollout isn't 100? Like 97? Is that done randomly then, or is it always false?

Should fallback to the original calculation - so random

**Comment by daveleek** [comment]
Yes, there's a random calculation and compared with stickiness

**Pull request merged**
